site_name: Bootcamp de Programación 2024
copyright: Copyright &copy; 2023 
repo_name: GitHub
nav:
    - "Bienvenido": 'index.md'
    - "Programa Académico": 'programa.md'
    - "Metodología": 'metodologia.md'
    - "Metodo de Pagos": 'pagos.md'
    - "Certificado": 'certificado.md'

theme:
  language: es
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
  font:
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
  features:
    - toc.follow
    - navigation.indexes
    - navigation.prune
    - navigation.footer
    - header.autohide
    - content.code.annotate 
    - content.code.select
    - content.code.copy
    - content.action.edit
    - search.share


markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  version:
    provider: mike
